services:
  pyspark:
    hostname: pyspark
    image: jupyter/pyspark-notebook:latest
    container_name: pyspark
    environment:
      - SPARK_OPTS=--driver-java-options=-Djava.net.preferIPv4Stack=true
    volumes:
      - "${DATA_PATH}:/home/jovyan/work"  # Bind mount local directory
    ports:
      - "8888:8888"  # Jupyter Notebook interface
      - "4040:4040"  # Spark UI
    networks:
      - tejs_network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tejs_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - tejs_network

networks:
  tejs_network:

volumes:
  postgres_data: